### ISSUE TITLE
Tnt duper design not working AC on 1.20.4

### ISSUE THREAD

**Issue by VoidPollo** [SpaceWalkerRS/alternate-current#34]
Hey!
I've been using AC for a long time now, never encountered an issue until now.

I found a specific design for a tree farm, and in this case it doesn't use the traditional slime and coral mechanic to make it happen, I couldn't make it to work until AC was the only mod removed, I tried even with only AC installed and it still would stop launch/dupe the tnt.

tree farm chosen: https://youtu.be/aTww2A6QGPA

world download: https://www.mediafire.com/file_premium/y1wy373tl4mcl6r/TheySix_-_UTFX_Tree_Farm_V2.rar/file

**Comment by SpaceWalkerRS** [comment]
Thanks for the report. I'm familiar with this TNT duper design, and unfortunately this issue is not feasible for me to fix. In short, this design relies on one of the fundamental issues with redstone dust that AC tries to fix, which is that wire blocks update their power level multiple times before settling on their final value. The trick is to update the TNT right in between multiple updates of the wire block, to make it ignite. It's simply not doable to fix this issue without sacrificing performance.
